# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loaderConnector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loaderConnector.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15loaderConnector.proto\"2\n\x0cInputReading\x12\x10\n\x08reading1\x18\x01 \x01(\x02\x12\x10\n\x08reading2\x18\x02 \x01(\x02\":\n\rOutputReading\x12\x13\n\x0b\x66irstOutput\x18\x01 \x01(\x02\x12\x14\n\x0csecondOutput\x18\x02 \x01(\x02\x32?\n\x0fLoaderConnector\x12,\n\x0bModelLoader\x12\r.InputReading\x1a\x0e.OutputReadingb\x06proto3'
)




_INPUTREADING = _descriptor.Descriptor(
  name='InputReading',
  full_name='InputReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reading1', full_name='InputReading.reading1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reading2', full_name='InputReading.reading2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=75,
)


_OUTPUTREADING = _descriptor.Descriptor(
  name='OutputReading',
  full_name='OutputReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstOutput', full_name='OutputReading.firstOutput', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='secondOutput', full_name='OutputReading.secondOutput', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['InputReading'] = _INPUTREADING
DESCRIPTOR.message_types_by_name['OutputReading'] = _OUTPUTREADING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputReading = _reflection.GeneratedProtocolMessageType('InputReading', (_message.Message,), {
  'DESCRIPTOR' : _INPUTREADING,
  '__module__' : 'loaderConnector_pb2'
  # @@protoc_insertion_point(class_scope:InputReading)
  })
_sym_db.RegisterMessage(InputReading)

OutputReading = _reflection.GeneratedProtocolMessageType('OutputReading', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTREADING,
  '__module__' : 'loaderConnector_pb2'
  # @@protoc_insertion_point(class_scope:OutputReading)
  })
_sym_db.RegisterMessage(OutputReading)



_LOADERCONNECTOR = _descriptor.ServiceDescriptor(
  name='LoaderConnector',
  full_name='LoaderConnector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=137,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='ModelLoader',
    full_name='LoaderConnector.ModelLoader',
    index=0,
    containing_service=None,
    input_type=_INPUTREADING,
    output_type=_OUTPUTREADING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOADERCONNECTOR)

DESCRIPTOR.services_by_name['LoaderConnector'] = _LOADERCONNECTOR

# @@protoc_insertion_point(module_scope)
